### ISSUE TITLE
Respect local::lib / perlbrew settings

### ISSUE THREAD

**Issue by ichesnokov** [shoichikaji/cpm#12]
Hi.

It would be great if App::cpm would respect already available environment settings of local::lib and perlbrew - and would install modules to the appropriate locations.

Thanks!

**Comment by shoichikaji** [comment]
What does "respect setting of perlbrew" mean?

**Comment by ichesnokov** [comment]
I mean that in the situation when your Perl interpreter is installed via perlbrew, it would be nice if cpm would install modules to the appropriate interpreter's directory. Maybe there should be more tight coupling with perlbrew for such case - I'm not sure about that, so maybe it should be a separate feature request.

**Comment by shoichikaji** [comment]
If you install cpm to your perlbrew controlled perl, and you want to install modules to the perl's global `@INC`, type `cpm install -g Module`.

**Comment by ichesnokov** [comment]
Good stuff, just tried, and it worked - even on different versions of perl installed via perlbrew - the issue can be closed then.
